# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
warnings_are_errors: false #ignore warnings in osx

matrix:
  include:
    - os: linux
      r: 
        - release
        - devel
      env: 
	- R_CODECOV=true
	- R_REMOTES_NO_ERRORS_FROM_WARNINGS=true # ignore errors from package remotes
    - os: osx
      r: 
        - release
        - devel
addons:
  homebrew:
    packages:
    - libgit2
