// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppMLPACK.h>
#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// mlpack_mst
Rcpp::NumericMatrix mlpack_mst(arma::mat& data);
RcppExport SEXP _emstreeR_mlpack_mst(SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type data(dataSEXP);
    rcpp_result_gen = Rcpp::wrap(mlpack_mst(data));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_emstreeR_mlpack_mst", (DL_FUNC) &_emstreeR_mlpack_mst, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_emstreeR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
