# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title \code{mlpack}'s Euclidean Minimum Spanning Tree
#'
#' @description Fast computes an EMST using the \code{mlpack C++} library.
#'
#' @param data a \code{matrix}.
#' @return a \code{matrix} containing each pair of start and end points
#' on its columns, and the distance between these points in order to 
#' produce the Minimum Spanning Tree.
#' @noRd
#'
mlpack_mst <- function(data) {
    .Call('_emstreeR_mlpack_mst', PACKAGE = 'emstreeR', data)
}

